name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build and Test
        run: ./gradlew build

      - name: Run JaCoCo Coverage
        run: ./gradlew jacocoTestReport

      - name: Check JaCoCo Coverage
        run: |
          COVERED=$(grep -oPm1 '(?<=<counter type="INSTRUCTION" covered=")[^\"]+' build/reports/jacoco/test/jacocoTestReport.xml)
          MISSED=$(grep -oPm1 '(?<=<counter type="INSTRUCTION" missed=")[^\"]+' build/reports/jacoco/test/jacocoTestReport.xml)
          TOTAL=$((COVERED+MISSED))
          if [ "$TOTAL" -eq 0 ]; then
            echo "No coverage data found. Failing build."
            exit 1
          fi
          PERCENT=$(awk "BEGIN {print ($COVERED/($TOTAL))*100}")
          echo "Coverage: $PERCENT%"
          if (( $(echo "$PERCENT < 90" | bc -l) )); then
            echo "Coverage is below 90% ($PERCENT%)"
            exit 1
          fi

      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: build/reports/jacoco/**

      - name: Build Docker Image (Demo)
        run: docker build -t wishlist-service:ci-demo .
