name: Deploy

on:
  push:
    tags:
      - 'v*.*.*'  # Only run on version tags like v1.0.0
  workflow_dispatch:  # Allow manual trigger

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: ./gradlew build

      - name: Fake Deploy (Demo)
      - name: Publish Artifacts
        run: ./gradlew publish
